# Generated by Django 5.0.2 on 2024-04-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0014_normaluser_name_nurse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
