# Generated by Django 5.0.2 on 2024-04-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0015_nurse_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='has_requested',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
