# Generated by Django 5.0.2 on 2024-04-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0004_nursebooking_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursebooking',
            name='has_requested',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
