# Generated by Django 5.0.2 on 2024-04-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0009_remove_report_user_alter_report_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
