# Generated by Django 5.0.2 on 2024-04-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0005_nursebooking_has_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursebooking',
            name='has_requested',
        ),
    ]
