# Generated by Django 5.0.2 on 2024-04-15 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0010_alter_report_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='nurse',
            new_name='user',
        ),
    ]
